const fs = require("node:fs");
const path = require("node:path");
const childProcess = require("node:child_process");

const { findProjectRoot, updateRuntime } = require("../core/project");
const { ensureDir, slugify, timestampUtc } = require("../core/utils");

function createSpec(projectRoot, description) {
  const root = findProjectRoot(projectRoot);
  const specSlug = slugify(description).toUpperCase();
  const specId = `SPEC-${specSlug}-001`;
  const filePath = path.join(root, ".moai", "specs", `${specId}.md`);
  ensureDir(path.dirname(filePath));

  const content = `# ${specId}

## Summary

${description}

## Acceptance Criteria

- Implementation is compatible with Codex/OMX.
- Changes are verifiable via tests or command outputs.
- Documentation is updated when behavior changes.
`;

  fs.writeFileSync(filePath, content, "utf8");
  updateRuntime(root, { currentSpec: specId, lastCommand: "plan" });

  return {
    command: "plan",
    specId,
    specPath: path.relative(root, filePath),
    prompt: `Create or refine implementation for ${specId}: ${description}`
  };
}

function createWorkflowArtifact(projectRoot, command, summary = "", overrides = {}) {
  const root = findProjectRoot(projectRoot);
  const reportsDir = path.join(root, ".moai", "project", "reports");
  ensureDir(reportsDir);
  ensureDir(path.join(root, ".moai", "project", "codemaps"));

  const stamp = timestampUtc();
  const artifactPath = path.join(reportsDir, `${command}-${stamp}.md`);
  const effectiveSummary = summary || defaultSummary(command);
  const specId = overrides.specId || null;

  if (command === "project") {
    writeProjectDocs(root, effectiveSummary);
  }
  if (command === "codemaps") {
    fs.writeFileSync(
      path.join(root, ".moai", "project", "codemaps", "overview.md"),
      `# Codemaps\n\nUpdated at ${new Date().toISOString()}\n\nSummary: ${effectiveSummary}\n`,
      "utf8"
    );
  }

  const content = `# ${command}

- Timestamp: ${new Date().toISOString()}
- Summary: ${effectiveSummary}
- Spec: ${specId || "n/a"}
- Mode: compatibility

## Next Codex Prompt

${buildPrompt(command, effectiveSummary, specId)}
`;

  fs.writeFileSync(artifactPath, content, "utf8");
  updateRuntime(root, {
    currentSpec: specId,
    lastCommand: command
  });

  return {
    command,
    artifactPath: path.relative(root, artifactPath),
    summary: effectiveSummary,
    specId,
    prompt: buildPrompt(command, effectiveSummary, specId)
  };
}

function writeProjectDocs(root, summary) {
  fs.writeFileSync(
    path.join(root, ".moai", "project", "product.md"),
    `# Product\n\n${summary || "Project summary not provided yet."}\n`,
    "utf8"
  );
  fs.writeFileSync(
    path.join(root, ".moai", "project", "structure.md"),
    "# Structure\n\n- Generated by moai-adk-codex project workflow.\n",
    "utf8"
  );
  fs.writeFileSync(
    path.join(root, ".moai", "project", "tech.md"),
    "# Tech\n\n- Runtime: Codex CLI\n- Compatibility layer: moai-adk-codex\n",
    "utf8"
  );
}

function buildPrompt(command, summary, specId) {
  const header = specId ? `${command.toUpperCase()} ${specId}` : command.toUpperCase();
  return `${header}\n\nSummary: ${summary}\n\nUse Codex/OMX-compatible behavior and preserve .moai artifacts.`;
}

function defaultSummary(command) {
  const map = {
    project: "Refresh project-level compatibility docs.",
    run: "Advance the active SPEC using Codex-native execution.",
    sync: "Synchronize compatibility docs and workflow artifacts.",
    review: "Review current changes through the compatibility lens.",
    coverage: "Assess test coverage and gaps.",
    clean: "Identify dead code and cleanup candidates.",
    fix: "Apply a single-pass repair loop.",
    loop: "Repeat repair and verification until convergence.",
    codemaps: "Refresh architecture maps."
  };
  return map[command] || `${command} compatibility workflow`;
}

function maybeExecuteWithCodex(projectRoot, command, prompt) {
  const root = findProjectRoot(projectRoot);
  const result = childProcess.spawnSync(
    "codex",
    [
      "exec",
      "--dangerously-bypass-approvals-and-sandbox",
      "--cd",
      root,
      prompt
    ],
    {
      cwd: root,
      encoding: "utf8"
    }
  );

  return {
    command,
    exitCode: result.status,
    stdout: result.stdout?.trim() || "",
    stderr: result.stderr?.trim() || ""
  };
}

function runWorktreeCommand(projectRoot, args) {
  const [subcommand, ...rest] = args;
  const cwd = path.resolve(projectRoot);

  switch (subcommand) {
    case "list":
      return execGit(cwd, ["worktree", "list", "--porcelain"], "worktree list");
    case "status":
      return execGit(cwd, ["worktree", "list"], "worktree status");
    case "new":
      if (!rest[0]) {
        throw new Error("worktree new requires a name");
      }
      return execGit(cwd, ["worktree", "add", `../${rest[0]}`, "-b", rest[0]], "worktree new");
    case "remove":
      if (!rest[0]) {
        throw new Error("worktree remove requires a path");
      }
      return execGit(cwd, ["worktree", "remove", rest[0]], "worktree remove");
    default:
      throw new Error("supported worktree commands: list, status, new, remove");
  }
}

function execGit(cwd, args, command) {
  const result = childProcess.spawnSync("git", args, { cwd, encoding: "utf8" });
  return {
    command,
    ok: result.status === 0,
    stdout: result.stdout.trim(),
    stderr: result.stderr.trim()
  };
}

module.exports = {
  createSpec,
  createWorkflowArtifact,
  maybeExecuteWithCodex,
  runWorktreeCommand
};
