package core

import "fmt"

type TemplateFile struct {
	Path    string
	Content string
}

func BuildTemplates(projectName, initializedAt string) []TemplateFile {
	return []TemplateFile{
		{
			Path: "AGENTS.md",
			Content: "# CoAI Compatibility Layer\n\n" +
				"This project was initialized by coai.\n\n" +
				"## Intent\n" +
				"- Preserve the familiar MoAI command vocabulary inside Codex.\n" +
				"- Treat `.coai/` as the public project contract.\n" +
				"- Use Codex/OMX as the execution engine.\n\n" +
				"## Suggested usage\n" +
				"- `coai project`\n" +
				"- `coai plan \"Describe the task\"`\n" +
				"- `coai run SPEC-EXAMPLE-001`\n" +
				"- `coai sync SPEC-EXAMPLE-001`\n",
		},
		{
			Path: ".coai/config/sections/project.yaml",
			Content: fmt.Sprintf(`project:
  name: "%s"
  initialized_at: "%s"
  compatibility_layer: "coai"
`, projectName, initializedAt),
		},
		{
			Path: ".coai/config/sections/workflow.yaml",
			Content: `workflow:
  execution_mode: cg
  runtime_engine: codex
  artifact_mode: prepare
`,
		},
		{
			Path: ".coai/config/sections/quality.yaml",
			Content: `constitution:
  development_mode: tdd
  test_coverage_target: 85
`,
		},
		{
			Path: ".coai/config/sections/llm.yaml",
			Content: `llm:
  current_runtime_mode: cg
  provider: codex
`,
		},
		{
			Path: ".coai/config/sections/compatibility.yaml",
			Content: `compatibility:
  execution_style: artifact_or_exec
  codex_exec_supported: true
  generated_by: coai
`,
		},
		{
			Path: ".coai/project/product.md",
			Content: fmt.Sprintf(`# Product

- Project: %s
- Scaffolded by: coai
- Goal: preserve MoAI workflows inside Codex
`, projectName),
		},
		{
			Path: ".coai/project/structure.md",
			Content: "# Structure\n\n" +
				"- `.coai/config/sections/`: compatibility config\n" +
				"- `.coai/project/`: generated workflow artifacts\n" +
				"- `.coai/state/`: runtime state\n" +
				"- `.coai/specs/`: SPEC documents generated by `coai plan`\n",
		},
		{
			Path: ".coai/project/tech.md",
			Content: `# Tech

- Runtime engine: Codex CLI
- Compatibility CLI: coai
- Default workflow mode: cg
`,
		},
		{
			Path:    ".coai/project/codemaps/overview.md",
			Content: "# Codemaps\n\nRun `coai codemaps` to refresh this overview.\n",
		},
		{
			Path: ".coai/state/runtime.json",
			Content: `{
  "currentRuntimeMode": "cg",
  "currentSpec": "",
  "lastCommand": "init"
}
`,
		},
	}
}
