function buildTemplates(context) {
  return [
    {
      path: "AGENTS.md",
      content: `# MoAI Codex Compatibility Layer

This project was initialized by moai-adk-codex.

## Intent
- Preserve the familiar MoAI command vocabulary inside Codex.
- Treat \`.moai/\` as the public project contract.
- Use Codex/OMX as the execution engine.

## Suggested usage
- \`moai project\`
- \`moai plan "Describe the task"\`
- \`moai run SPEC-EXAMPLE-001\`
- \`moai sync SPEC-EXAMPLE-001\`
`
    },
    {
      path: ".moai/config/sections/project.yaml",
      content: `project:
  name: "${context.projectName}"
  initialized_at: "${context.initializedAt}"
  compatibility_layer: "moai-adk-codex"
`
    },
    {
      path: ".moai/config/sections/workflow.yaml",
      content: `workflow:
  execution_mode: cg
  runtime_engine: codex
  artifact_mode: prepare
`
    },
    {
      path: ".moai/config/sections/quality.yaml",
      content: `constitution:
  development_mode: tdd
  test_coverage_target: 85
`
    },
    {
      path: ".moai/config/sections/llm.yaml",
      content: `llm:
  current_runtime_mode: cg
  provider: codex
`
    },
    {
      path: ".moai/config/sections/compatibility.yaml",
      content: `compatibility:
  execution_style: artifact_or_exec
  codex_exec_supported: true
  generated_by: moai-adk-codex
`
    },
    {
      path: ".moai/project/product.md",
      content: `# Product

- Project: ${context.projectName}
- Scaffolded by: moai-adk-codex
- Goal: preserve MoAI workflows inside Codex
`
    },
    {
      path: ".moai/project/structure.md",
      content: `# Structure

- \`.moai/config/sections/\`: compatibility config
- \`.moai/project/\`: generated workflow artifacts
- \`.moai/state/\`: runtime state
- \`.moai/specs/\`: SPEC documents generated by \`moai plan\`
`
    },
    {
      path: ".moai/project/tech.md",
      content: `# Tech

- Runtime engine: Codex CLI
- Compatibility CLI: moai-adk-codex
- Default workflow mode: cg
`
    },
    {
      path: ".moai/project/codemaps/overview.md",
      content: `# Codemaps

Run \`moai codemaps\` to refresh this overview.
`
    },
    {
      path: ".moai/state/runtime.json",
      content: JSON.stringify(
        {
          currentRuntimeMode: "cg",
          currentSpec: null,
          lastCommand: "init"
        },
        null,
        2
      ) + "\n"
    }
  ];
}

module.exports = {
  buildTemplates
};
